/* Web presentation based on the team's Android layouts, not an Android runtime.
 * Source: ProgrammerPerederko/SeniorLink @ 0de362c94d625140f221c9d46f076fcaec7d8de6.
 * Original artwork lives unchanged in assets/app. All controls below are visual.
 */
(() => {
  'use strict';
  const status = '<div class="native-status"><span>9:41</span><span>▮▮▮ &nbsp; ▰</span></div>';
  const footer = step => `<div class="native-onboarding-nav"><span>Pular</span><span class="native-dots">${[0,1,2].map(i=>`<i class="${i === step ? 'selected' : ''}"></i>`).join('')}</span><span class="native-next">→</span></div>`;
  const page = content => `<div class="native-screen">${status}${content}</div>`;
  const action = (text,outline = false) => `<div class="native-action ${outline ? 'outline' : ''}">${text}</div>`;
  const heading = (title,description) => `<span class="native-back">← Voltar</span><h2>${title}</h2><p>${description}</p>`;
  const field = text => `<div class="native-field">${text}</div>`;
  const feature = (emoji,title,description,color) => `<div class="native-tile ${color}"><span>${emoji}</span><div><strong>${title}</strong><small>${description}</small></div></div>`;
  const scenes = [
    {name:'Boas-vindas',short:'Boas-vindas',heading:'Cuidado hoje.<br><em>Mais liberdade amanhã.</em>',description:'Mais conexão para todas as fases da vida.',icon:'heart',render:()=>page(`<div class="native-splash"><img src="./assets/app/seniorlink-logo.jpeg" alt=""></div>${footer(0)}`)},
    {name:'Cuidado entre gerações',short:'Cuidado',heading:'Perto de quem<br><em>faz parte da sua vida.</em>',description:'Autonomia para você. Tranquilidade para quem cuida.',icon:'users',render:()=>page(`<div class="native-onboarding"><img class="native-care" src="./assets/app/onboarding-cuidado.png" alt=""><h2>Cuidado hoje,<br>mais liberdade amanhã</h2><p>O SeniorLink ajuda você a estar sempre por perto, com segurança e praticidade.</p></div>${footer(1)}`)},
    {name:'Sempre por perto',short:'Conexão',heading:'A distância diminui.<br><em>O cuidado aproxima.</em>',description:'Uma conexão com as pessoas em quem você confia.',icon:'pin',render:()=>page(`<div class="native-onboarding native-location-intro"><h2>Sempre por perto</h2><p>Acompanhe a localização e mantenha quem você ama conectado com mais tranquilidade.</p><img src="./assets/app/onboarding-localizacao.png" alt=""></div>${footer(1)}`)},
    {name:'Aprenda no seu ritmo',short:'Autonomia',heading:'Cada descoberta,<br><em>mais autonomia.</em>',description:'Orientações simples. Um passo de cada vez.',icon:'book',render:()=>page(`<div class="native-onboarding"><div class="native-books">📚</div><h2>Aprenda no seu ritmo</h2><p>Descubra como usar seu celular e o SeniorLink com orientações simples, passo a passo.</p></div>${footer(2)}`)},
    {name:'Tela inicial',short:'Início',heading:'Olá, Maria!<br><em>Seu dia, mais simples.</em>',description:'Perfil, lembretes, aprendizado e apoio, no mesmo lugar.',icon:'home',render:()=>page(`<div class="native-home"><div class="native-greeting"><div><h2>Olá, Maria! 👋</h2><p>Que bom te ver por aqui!</p></div><span>👤</span></div><div class="native-grid">${feature('👤','Meu perfil','Seus dados importantes','blue')}${feature('📍','Localização','Ver sua localização','teal')}${feature('🔔','Lembretes','Não esqueça do importante','orange')}${feature('🧩','Aprender','Tutoriais e dicas','blue')}</div><div class="native-emergency-row"><span>🆘</span><div><strong>Emergência</strong><small>Toque para acionar ajuda</small></div></div><p class="native-home-caption">Cuidado, autonomia e conexão</p></div><div class="native-bottom">${[['⌂','Início'],['📍','Localização'],['🔔','Lembretes'],['👤','Perfil']].map(([emoji,text])=>`<span><b>${emoji}</b>${text}</span>`).join('')}</div>`)},
    {name:'Meu perfil',short:'Perfil',heading:'Sua história.<br><em>Seu cuidado.</em>',description:'Informações importantes para acompanhar você.',icon:'user',render:()=>page(`<div class="native-body native-profile">${heading('Meu perfil','Informações importantes para sua segurança.')}<div class="native-fields">${['Nome completo','Data de nascimento','Tipo sanguíneo','Alergias','Medicamentos em uso','Condições importantes','Contato de confiança','Telefone do contato'].map(field).join('')}</div>${action('Salvar informações')}<small class="native-note">Protótipo: os dados ainda não são salvos.</small></div>`)},
    {name:'Localização',short:'Localização',heading:'Uma rede de confiança.<br><em>Sempre por perto.</em>',description:'Compartilhar o caminho também é uma forma de cuidar.',icon:'pin',render:()=>page(`<div class="native-body">${heading('Localização','Acompanhe sua localização e compartilhe com uma pessoa de confiança.')}<div class="native-card"><strong>📍 Sua localização</strong><p>O GPS será conectado em uma próxima etapa.</p>${action('Ativar localização')}</div><div class="native-card"><strong>Pessoa de confiança</strong><p>Você poderá configurar quem recebe sua localização.</p>${action('Configurar contato',true)}</div><small class="native-note">Protótipo: ainda não acessa o GPS nem compartilha a localização em tempo real.</small></div>`)},
    {name:'Lembretes',short:'Lembretes',heading:'No seu tempo.<br><em>Na hora certa.</em>',description:'Espaço para os pequenos cuidados de todos os dias.',icon:'bell',render:()=>page(`<div class="native-body">${heading('Lembretes','Organize suas atividades do dia a dia.')}<div class="native-fields">${field('O que precisa lembrar?')}${field('Horário (ex.: 08:00)')}</div>${action('Adicionar lembrete')}<h3>Meus lembretes</h3><p>Você ainda não adicionou lembretes.</p><small class="native-note">Protótipo: os lembretes não geram notificações e são apagados ao fechar esta tela.</small></div>`)},
    {name:'Aprender',short:'Aprender',heading:'A tecnologia<br><em>também é para você.</em>',description:'Mais confiança para explorar novas possibilidades.',icon:'book',render:()=>page(`<div class="native-body native-learning">${heading('Aprender','Aprenda a usar seu celular passo a passo.')}${['Como aumentar o tamanho das letras','Como fazer uma ligação','Como usar o Wi-Fi','Como enviar uma mensagem'].map(text=>`<div class="native-card"><strong>${text}</strong>${action('Ver passo a passo',true)}</div>`).join('')}</div>`)},
    {name:'Emergência',short:'Apoio',heading:'Você pode<br><em>contar com alguém.</em>',description:'Sua rede de apoio faz parte do cuidado.',icon:'phone',render:()=>page(`<div class="native-body">${heading('Emergência','Esta área reúne opções para pedir ajuda.')}<div class="native-card native-sos-card"><strong>Precisa de ajuda?</strong><p>Se estiver em perigo imediato, procure ajuda pelos serviços de emergência locais.</p>${action('Pedir ajuda')}</div>${action('Contato de confiança — configurar depois',true)}<small class="native-note">Demonstração visual. Nenhum alerta ou chamada é realizado.</small></div>`)}
  ];
  window.SeniorLinkScreens = Object.freeze(scenes);
})();
